import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import SideBar from "@/components/SideBar";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <SidebarProvider>
      <div className="flex h-screen">
        <SideBar />
        <main className="flex-1 overflow-auto w-[82vw]">
          <Toaster/>
          <div className="flex items-center gap-2 p-4 border-b md:hidden">
            <SidebarTrigger className="h-8 w-8" />
            <h1 className="text-lg font-semibold">Dashboard</h1>
          </div>

          <div className="hidden md:flex items-center gap-2 p-4 border-b">
            <SidebarTrigger className="h-8 w-8" />
            <h1 className="text-lg font-semibold">Dashboard</h1>
          </div>

          <div className="p-4">{children}</div>
        </main>
      </div>
    </SidebarProvider>
  );
}
